### ISSUE TITLE
Implicit global variables in orvibo-node.js

### ISSUE THREAD

**Issue by mwittig** [thexperiments/pimatic-orvibo#2]
As mentioned in https://forum.pimatic.org/topic/1731/generic-modules-in-plugins-bluebird you’re using implicit global variables in orvibo-node.js. You shouldn’t do that as it may have unexpected side effects. Use local variables instead.

**Comment by mwittig** [comment]
Should be fixed by PR #3

**Comment by thexperiments** [comment]
Thanks
